### ISSUE TITLE
strange result in toy dataset experiment 

### ISSUE THREAD

**Issue by LeeJuly30** [Nrgeup/SentiGAN#1]
Hi, wang 
Very nice work and thanks for your sharing. When i run the toy dataset code i find that the NLL loss increased slowly to around 9.30 for about 120 epochs and then drop to 8.18 during adversarial training, which is quit different from the result reported in paper. Since i didn't change the code so is there anything
wrong with the toy dataset code?

**Comment by Nrgeup** [comment]
Thank you for your question. The training process of the generative adversarial network is very unstable, I suggest you repeat it a few times. The result in our paper is the best one we have run.

**Comment by Nrgeup** [comment]
@LeeJuly30 
Thank you for your question. The training process of the generative adversarial network is very unstable, I suggest you repeat it a few times. The result in our paper is the best one we have run.

**Comment by LeeJuly30** [comment]
Thanks for your prompt reply. I have tested for several times and get the similar result. I also notice that the NLL loss only begin to decrease when the discriminator loss is pretty low (about 0.0006), after i change the total batch of adversarial training to 250, the NLL loss drop to 7.20 but the averaged 4-gram self bleu score is 0.56 which means that the generator suffers from mode collapse problem :)
